version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "brain-tasks-app"
    EKS_CLUSTER_NAME: "brain-tasks-cluster"
    K8S_NAMESPACE: "default"

phases:
  install:
    commands:
      - echo "Installing kubectl..."
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x ./kubectl && mv ./kubectl /usr/local/bin/kubectl
      - kubectl version --client

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-8)
      - if [ -z "$IMAGE_TAG" ]; then IMAGE_TAG=latest; fi
      - echo "Image will be tagged as $IMAGE_TAG"

  build:
    commands:
      - echo "Build started on $(date)"
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $REPOSITORY_URI:latest

  post_build:
    commands:
      - echo "Pushing image to ECR..."
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest

      - echo "Updating kubeconfig..."
      - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_DEFAULT_REGION

      - echo "Deploying to EKS..."
      - sed -i "s|367061003285.dkr.ecr.eu-north-1.amazonaws.com/brain-tasks-app:latest|$REPOSITORY_URI:$IMAGE_TAG|g" k8s/deployment.yaml
      - kubectl apply -f k8s/deployment.yaml -n $K8S_NAMESPACE
      - kubectl apply -f k8s/service.yaml -n $K8S_NAMESPACE
      - kubectl rollout status deployment/brain-tasks-app -n $K8S_NAMESPACE --timeout=180s
      - kubectl get svc brain-tasks-app-svc -n $K8S_NAMESPACE
